"use client"

import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export interface MatchingPDFData {
  maleName?: string
  femaleName?: string
  maleDetails?: {
    nakshatra?: string
    rashi?: string
  }
  femaleDetails?: {
    nakshatra?: string
    rashi?: string
  }
  totalScore: number
  maxScore: number
  percentage: number
  verdict: string
  kootas: Array<{
    koota: string
    scored: number
    maxPoints: number
    status?: string
    description?: string
  }>
  doshas?: string[]
  recommendations?: string[]
}

export function generateMatchingPDF(data: MatchingPDFData): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let yPos = 20

  const addSectionHeader = (title: string, y: number): number => {
    doc.setFillColor(147, 51, 234)
    doc.rect(14, y, pageWidth - 28, 10, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont("helvetica", "bold")
    doc.text(title, 20, y + 7)
    doc.setTextColor(0, 0, 0)
    return y + 15
  }

  // Title
  doc.setFillColor(147, 51, 234)
  doc.rect(0, 0, pageWidth, 36, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont("helvetica", "bold")
  doc.text("KUNDLI MATCHING REPORT", pageWidth / 2, 20, { align: "center" })
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text("Generated by VedicAstro", pageWidth / 2, 30, { align: "center" })
  doc.setTextColor(0, 0, 0)
  yPos = 50

  // Participants
  yPos = addSectionHeader("Participants", yPos)
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  const maleLabel = data.maleName ? `Male: ${data.maleName}` : "Male"
  const femaleLabel = data.femaleName ? `Female: ${data.femaleName}` : "Female"

  doc.setFont("helvetica", "bold")
  doc.text(maleLabel, 20, yPos)
  doc.setFont("helvetica", "normal")
  doc.text(
    `Nakshatra: ${data.maleDetails?.nakshatra || "N/A"} | Rashi: ${data.maleDetails?.rashi || "N/A"}`,
    20,
    yPos + 6
  )
  doc.setFont("helvetica", "bold")
  doc.text(femaleLabel, 20, yPos + 16)
  doc.setFont("helvetica", "normal")
  doc.text(
    `Nakshatra: ${data.femaleDetails?.nakshatra || "N/A"} | Rashi: ${data.femaleDetails?.rashi || "N/A"}`,
    20,
    yPos + 22
  )
  yPos += 34

  // Summary
  yPos = addSectionHeader("Summary", yPos)
  doc.setFont("helvetica", "normal")
  doc.text(`Total Score: ${data.totalScore}/${data.maxScore}`, 20, yPos)
  doc.text(`Compatibility: ${data.percentage}%`, 20, yPos + 6)
  doc.text(`Verdict: ${data.verdict}`, 20, yPos + 12)
  yPos += 22

  // Koota table
  yPos = addSectionHeader("Koota Breakdown", yPos)
  const kootaRows = data.kootas.map((k) => [
    k.koota,
    `${k.scored}`,
    `${k.maxPoints}`,
    k.status || "-",
    k.description || "-",
  ])

  autoTable(doc, {
    startY: yPos,
    head: [["Koota", "Score", "Max", "Status", "Notes"]],
    body: kootaRows,
    theme: "striped",
    headStyles: { fillColor: [147, 51, 234] },
    styles: { fontSize: 9, cellPadding: 2 },
    columnStyles: { 4: { cellWidth: 70 } },
    margin: { left: 14, right: 14 },
  })

  yPos = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : yPos + 10

  // Doshas
  if (data.doshas && data.doshas.length > 0) {
    if (yPos > 250) {
      doc.addPage()
      yPos = 20
    }
    yPos = addSectionHeader("Doshas", yPos)
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    data.doshas.slice(0, 5).forEach((dosha, idx) => {
      const lines = doc.splitTextToSize(`${idx + 1}. ${dosha}`, pageWidth - 40)
      doc.text(lines, 20, yPos)
      yPos += lines.length * 5 + 2
    })
  }

  // Recommendations
  if (data.recommendations && data.recommendations.length > 0) {
    if (yPos > 240) {
      doc.addPage()
      yPos = 20
    }
    yPos = addSectionHeader("Recommendations", yPos)
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    data.recommendations.slice(0, 5).forEach((rec, idx) => {
      const lines = doc.splitTextToSize(`${idx + 1}. ${rec}`, pageWidth - 40)
      doc.text(lines, 20, yPos)
      yPos += lines.length * 5 + 2
    })
  }

  const dateStr = new Date().toISOString().split("T")[0]
  const namePart = [data.maleName, data.femaleName].filter(Boolean).join("_")
  const safeName = namePart ? `${namePart}_` : ""
  const fileName = `${safeName}Kundli_Matching_${dateStr}.pdf`.replace(/\s+/g, "_")

  doc.save(fileName)
}
