"use client"

import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

interface KundliPDFData {
  birthDetails: {
    name: string
    dateOfBirth: string
    timeOfBirth: string
    placeOfBirth: string
  }
  kundli: {
    ascendant: {
      sign: string
      nakshatra: string
      pada: number
      degree: string
    }
    moonSign: { name: string; english: string }
    sunSign: { name: string; english: string }
  }
  planets: Array<{
    name: string
    sign: string
    nakshatra: string
    house: number
    degree: string
    isRetrograde: boolean
  }>
  dasha: {
    currentDasha: string
    timeline: Array<{
      planet: string
      startDate: string
      endDate: string
      duration: string
    }>
  }
  yogas: Array<{
    name: string
    description: string
    strength: string
  }>
  doshas: Array<{
    name: string
    description: string
    severity: string
    remedies: string[]
  }>
}

export function generateKundliPDF(data: KundliPDFData): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let yPos = 20

  // Helper function to add section header
  const addSectionHeader = (title: string, y: number): number => {
    doc.setFillColor(147, 51, 234) // Purple
    doc.rect(14, y, pageWidth - 28, 10, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont("helvetica", "bold")
    doc.text(title, 20, y + 7)
    doc.setTextColor(0, 0, 0)
    return y + 15
  }

  // Title
  doc.setFillColor(147, 51, 234)
  doc.rect(0, 0, pageWidth, 40, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont("helvetica", "bold")
  doc.text("VEDIC KUNDLI REPORT", pageWidth / 2, 20, { align: "center" })
  doc.setFontSize(12)
  doc.setFont("helvetica", "normal")
  doc.text("Generated by Zodii", pageWidth / 2, 32, { align: "center" })
  doc.setTextColor(0, 0, 0)
  yPos = 55

  // Birth Details Section
  yPos = addSectionHeader("Birth Details", yPos)
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  
  const birthDetails = [
    ["Name:", data.birthDetails.name],
    ["Date of Birth:", data.birthDetails.dateOfBirth],
    ["Time of Birth:", data.birthDetails.timeOfBirth],
    ["Place of Birth:", data.birthDetails.placeOfBirth],
  ]
  
  birthDetails.forEach(([label, value], index) => {
    doc.setFont("helvetica", "bold")
    doc.text(label, 20, yPos + index * 7)
    doc.setFont("helvetica", "normal")
    doc.text(value || "N/A", 70, yPos + index * 7)
  })
  yPos += 35

  // Ascendant & Signs Section
  yPos = addSectionHeader("Ascendant & Key Signs", yPos)
  
  const signDetails = [
    ["Ascendant (Lagna):", `${data.kundli.ascendant.sign} - ${data.kundli.ascendant.degree}`],
    ["Nakshatra:", `${data.kundli.ascendant.nakshatra} (Pada ${data.kundli.ascendant.pada})`],
    ["Moon Sign (Rashi):", `${data.kundli.moonSign.name} (${data.kundli.moonSign.english})`],
    ["Sun Sign:", `${data.kundli.sunSign.name} (${data.kundli.sunSign.english})`],
  ]
  
  signDetails.forEach(([label, value], index) => {
    doc.setFont("helvetica", "bold")
    doc.text(label, 20, yPos + index * 7)
    doc.setFont("helvetica", "normal")
    doc.text(value, 80, yPos + index * 7)
  })
  yPos += 40

  // Planetary Positions Table
  yPos = addSectionHeader("Planetary Positions (Graha Sthiti)", yPos)
  
  const planetRows = data.planets.map((planet) => [
    planet.name,
    planet.sign,
    planet.nakshatra,
    planet.house.toString(),
    planet.degree,
    planet.isRetrograde ? "R" : "-",
  ])

  autoTable(doc, {
    startY: yPos,
    head: [["Planet", "Sign", "Nakshatra", "House", "Degree", "Retro"]],
    body: planetRows,
    theme: "striped",
    headStyles: { fillColor: [147, 51, 234] },
    styles: { fontSize: 9, cellPadding: 2 },
    margin: { left: 14, right: 14 },
  })

  yPos = (doc as any).lastAutoTable.finalY + 15

  // Check if we need a new page
  if (yPos > 240) {
    doc.addPage()
    yPos = 20
  }

  // Dasha Timeline
  yPos = addSectionHeader("Vimshottari Dasha Timeline", yPos)
  
  doc.setFontSize(10)
  doc.setFont("helvetica", "bold")
  doc.text(`Current Mahadasha: ${data.dasha.currentDasha}`, 20, yPos)
  yPos += 10

  const dashaRows = data.dasha.timeline.slice(0, 6).map((d) => [
    d.planet,
    d.startDate,
    d.endDate,
    d.duration,
  ])

  autoTable(doc, {
    startY: yPos,
    head: [["Mahadasha", "Start Date", "End Date", "Duration"]],
    body: dashaRows,
    theme: "striped",
    headStyles: { fillColor: [147, 51, 234] },
    styles: { fontSize: 9, cellPadding: 2 },
    margin: { left: 14, right: 14 },
  })

  yPos = (doc as any).lastAutoTable.finalY + 15

  // Check if we need a new page
  if (yPos > 200) {
    doc.addPage()
    yPos = 20
  }

  // Yogas Section
  if (data.yogas.length > 0) {
    yPos = addSectionHeader("Yogas (Planetary Combinations)", yPos)
    
    data.yogas.forEach((yoga, index) => {
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }
      doc.setFont("helvetica", "bold")
      doc.setFontSize(10)
      doc.text(`${index + 1}. ${yoga.name} (${yoga.strength})`, 20, yPos)
      doc.setFont("helvetica", "normal")
      doc.setFontSize(9)
      
      const lines = doc.splitTextToSize(yoga.description, pageWidth - 50)
      doc.text(lines, 25, yPos + 5)
      yPos += 5 + lines.length * 5 + 5
    })
    yPos += 5
  }

  // Check if we need a new page
  if (yPos > 200) {
    doc.addPage()
    yPos = 20
  }

  // Doshas Section
  if (data.doshas.length > 0) {
    yPos = addSectionHeader("Doshas & Remedies", yPos)
    
    data.doshas.forEach((dosha, index) => {
      if (yPos > 250) {
        doc.addPage()
        yPos = 20
      }
      
      // Dosha name and severity
      doc.setFont("helvetica", "bold")
      doc.setFontSize(10)
      const severityColor = dosha.severity === "high" ? [220, 38, 38] : 
                           dosha.severity === "medium" ? [245, 158, 11] : [34, 197, 94]
      doc.setTextColor(severityColor[0], severityColor[1], severityColor[2])
      doc.text(`${index + 1}. ${dosha.name} (${dosha.severity.toUpperCase()})`, 20, yPos)
      doc.setTextColor(0, 0, 0)
      
      // Description
      doc.setFont("helvetica", "normal")
      doc.setFontSize(9)
      const descLines = doc.splitTextToSize(dosha.description, pageWidth - 50)
      doc.text(descLines, 25, yPos + 5)
      yPos += 5 + descLines.length * 4 + 3
      
      // Remedies
      doc.setFont("helvetica", "italic")
      doc.text("Remedies:", 25, yPos)
      yPos += 5
      dosha.remedies.slice(0, 3).forEach((remedy) => {
        if (yPos > 280) {
          doc.addPage()
          yPos = 20
        }
        doc.text(`• ${remedy}`, 30, yPos)
        yPos += 5
      })
      yPos += 5
    })
  }

  // Footer on each page
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text(
      `Page ${i} of ${pageCount} | Generated on ${new Date().toLocaleDateString()} | zodii.in`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    )
  }

  // Save the PDF
  const fileName = `${data.birthDetails.name.replace(/\s+/g, "_")}_Kundli_${new Date().toISOString().split("T")[0]}.pdf`
  doc.save(fileName)
}
